sudo: false
language: node_js
notifications:
  email: false
node_js:
- '6'
before_install: scripts/before_install.sh
before_script: scripts/before_script.sh
script: scripts/script.sh
after_script: scripts/after_script.sh
after_failure: scripts/after_failure.sh
after_success: scripts/after_success.sh
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
